[versions]
agp = "9.2.1"
kotlin = "2.4.0"
ksp = "2.3.9"

libxposed-api = "102.0.0"
libxposed-service = "102.0.0"
kavaref = "1.1.0"
koin = "4.2.2"
palette = "1.0.0"
kotlinx-coroutines = "1.11.0"
kotlinx-serialization = "1.11.0"

[libraries]
libxposed-api = { module = "io.github.libxposed:api", version.ref = "libxposed-api" }
libxposed-service = { module = "io.github.libxposed:service", version.ref = "libxposed-service" }
kavaref-core = { module = "com.highcapable.kavaref:kavaref-core", version.ref = "kavaref" }
kavaref-android = { module = "com.highcapable.kavaref:kavaref-android", version.ref = "kavaref" }
kavaref-extension = { module = "com.highcapable.kavaref:kavaref-extension", version.ref = "kavaref" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "palette" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
